cloud:
  aws:
    credentials:
      access-key: AKIAUSIA7IIRP27Z4O6M
      secret-key: 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
    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: dishimagespring


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090